version: "3.7"

services:
  portal-app:
    container_name: portal-covid-app
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
        - portal-covid-backend:portal-covid-backend
    ports:
      - 8080:80
      - 44443:443
    networks:
    - all_containers_databases_portal-databases-network

networks:
  all_containers_databases_portal-databases-network:
    external: true